apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-crds
  namespace: infra-tools
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: infra-tools
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 75.16.1
    helm:
      valuesObject:
        crds:
          enabled: true
        prometheus:
          enabled: false
        alertmanager:
          enabled: false
        grafana:
          enabled: false
        kube-state-metrics:
          enabled: false
        prometheus-node-exporter:
          enabled: false
  syncPolicy:
    automated:
      prune: false   # CRD-и не видаляємо автоматично
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
