apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
spec:
  destination:
    namespace: infra-tools
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://prometheus-community.github.io/helm-charts"
    chart: kube-prometheus-stack
    targetRevision: 75.16.1
    helm:
      valuesObject:
        defaultRules:
          create: false   # без купи дефолтних алертів
        crds:
          enabled: true
        prometheus:
          ingress:
            enabled: false
          prometheusSpec:
            resources:
              requests:
                cpu: 200m
                memory: 512Mi
              limits:
                cpu: 500m
                memory: 1Gi
        alertmanager:
          enabled: false   # прибрали повністю
        grafana:
          ingress:
            enabled: false
          adminPassword: prom-operator
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
        kube-state-metrics:
          enabled: true   # залишаємо, бо потрібен для метрик k8s
        prometheus-node-exporter:
          enabled: true   # щоб збирати CPU/Memory/FS з нод
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
      - ServerSideApply=true
