apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
spec:
  destination:
    namespace: infra-tools
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://prometheus-community.github.io/helm-charts"
    chart: kube-prometheus-stack
    targetRevision: 71.2.0
    helm:
      valuesObject:
        crds:
          enabled: true
        grafana:
          ingress:
            enabled: false
        prometheus:
          ingress:
            enabled: false
        alertmanager:
          enabled: false
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true