apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-pushgateway
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-pushgateway
    targetRevision: 2.10.0   # Актуальна стабільна версія (можна перевірити helm search repo)
    helm:
      releaseName: prometheus-pushgateway
      valuesObject:
        service:
          type: ClusterIP
          port: 9091
  destination:
    namespace: infra-tools
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
