apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: development
spec:
  project: default
  destination:
    namespace: development
    server: https://kubernetes.default.svc
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mlflow
    targetRevision: 8.3.1   # актуальна версія на ArtifactHub
    helm:
      valuesObject:
        service:
          type: ClusterIP
          port: 5000
        persistence:
          enabled: false    # легке розгортання, без PVC
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        metrics:
          enabled: true
        serviceMonitor:
          enabled: true
          additionalLabels:
            release: prometheus-operator
  syncPolicy:
    syncOptions:
    - Replace=true
    - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
