apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: mlflow
    targetRevision: 1.6.2
    helm:
      releaseName: mlflow
      valuesObject:
        service:
          type: ClusterIP
          port: 5000

        auth:
          enabled: false

        # Використовуємо зовнішній Postgres (розгорнутий окремо)
        postgresql:
          enabled: false

        # Підтягуємо секрет із MinIO + Postgres конфігами
        extraEnvVars:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: mlflow-secrets
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: mlflow-secrets
                key: AWS_SECRET_ACCESS_KEY
          - name: MLFLOW_S3_ENDPOINT_URL
            valueFrom:
              secretKeyRef:
                name: mlflow-secrets
                key: MLFLOW_S3_ENDPOINT_URL
          - name: MLFLOW_BACKEND_STORE_URI
            valueFrom:
              secretKeyRef:
                name: mlflow-secrets
                key: MLFLOW_BACKEND_STORE_URI
          - name: MLFLOW_ARTIFACT_ROOT
            valueFrom:
              secretKeyRef:
                name: mlflow-secrets
                key: MLFLOW_ARTIFACT_ROOT

  destination:
    namespace: application
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
