apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: infra-tools   # де працює ArgoCD
spec:
  project: default
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: mlflow
    targetRevision: 1.6.2
    helm:
      releaseName: mlflow
      valuesObject:
        service:
          type: ClusterIP
          port: 5000

        # Локальне сховище артефактів (тимчасове)
        defaultArtifactRoot: file:///mlruns

        # Без авторизації (тільки для dev/test)
        auth:
          enabled: false

        # Вбудована PostgreSQL (без persistence)
        postgresql:
          enabled: true
          primary:
            persistence:
              enabled: false
          auth:
            postgresPassword: mlflowpass
            username: mlflow
            password: mlflowpass
            database: mlflowdb

        # Вбудований MinIO (без persistence)
        minio:
          enabled: true
          persistence:
            enabled: false

        # Tracking server (без persistence)
        tracking:
          persistence:
            enabled: false

  destination:
    namespace: application   # сюди розгорнеться MLflow
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
