apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-redis
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: 20.2.1   # актуальна версія (можеш перевірити helm search repo bitnami/redis)
    helm:
      releaseName: test-redis
      valuesObject:
        architecture: standalone
        auth:
          enabled: false
        master:
          persistence:
            enabled: false
  destination:
    namespace: application
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
