apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pytorch
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: application
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: pytorch
    targetRevision: 2.1.11   # актуальна версія на сьогодні
    helm:
      valuesObject:
        image:
          repository: docker.io/bitnami/pytorch
          tag: 2.3.1-debian-12-r10   # легкий офіційний тег
        service:
          type: ClusterIP
          port: 8888   # доступ до Jupyter Notebook
        jupyterPassword: "ml-demo"   # простий пароль для входу
        persistence:
          enabled: false             # без PVC, легке розгортання
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
  syncPolicy:
    syncOptions:
      - Replace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
