apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: torchserve-real
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: application
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://intel.github.io/helm-charts
    chart: torchserve
    targetRevision: 0.1.0
    helm:
      valuesObject:
        image:
          repository: pytorch/torchserve
          tag: 0.8.2
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        metrics:
          enabled: true
        serviceMonitor:
          enabled: true
          additionalLabels:
            release: prometheus-operator
        modelStore:
          models:
            densenet161.mar:
              url: https://torchserve.pytorch.org/mar_files/densenet161.mar
  syncPolicy:
    syncOptions:
      - Replace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
