apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pytorch-observability
spec:
  destination:
    namespace: application
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: pytorch
    targetRevision: 4.3.31  # актуальна версія
    helm:
      valuesObject:
        # Основні налаштування
        image:
          repository: docker.io/bitnami/pytorch
          tag: 2.3.1-debian-12-r10
        service:
          type: ClusterIP
          port: 8888
        persistence:
          enabled: false
        jupyterPassword: "ml-demo"
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi

        # Метрики та Prometheus
        metrics:
          enabled: true
          service:
            port: 8888
        serviceMonitor:
          enabled: true
          interval: 30s
          additionalLabels:
            release: prometheus-operator
          
        # Логи → Loki (через sidecar)
        logs:
          enabled: true
          sidecar:
            enabled: true
            path: /opt/bitnami/pytorch/logs
            logLevel: info
            configs:
              - name: pytorch-logs
                file: /opt/bitnami/pytorch/logs/*.log

  syncPolicy:
    syncOptions:
      - Replace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
